In [95]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import nltk

In [96]:
data = pd.read_csv('C:\\Users\\user\\Documents\\GitHub\\nlp_project\\data\\test_questions.csv')

In [97]:
data['question1'] = data['question1'].str.lower()
data['question2'] = data['question2'].str.lower()
data.head(15)

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,what is the step by step guide to invest in sh...,what is the step by step guide to invest in sh...,0
1,1,3,4,what is the story of kohinoor (koh-i-noor) dia...,what would happen if the indian government sto...,0
2,2,5,6,how can i increase the speed of my internet co...,how can internet speed be increased by hacking...,0
3,3,7,8,why am i mentally very lonely? how can i solve...,find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"which one dissolve in water quikly sugar, salt...",which fish would survive in salt water?,0
5,5,11,12,astrology: i am a capricorn sun cap moon and c...,"i'm a triple capricorn (sun, moon and ascendan...",1
6,6,13,14,should i buy tiago?,what keeps childern active and far from phone ...,0
7,7,15,16,how can i be a good geologist?,what should i do to be a great geologist?,1
8,8,17,18,when do you use シ instead of し?,"when do you use ""&"" instead of ""and""?",0
9,9,19,20,motorola (company): can i hack my charter moto...,how do i hack motorola dcx3400 for free internet?,0
10,10,21,22,method to find separation of slits using fresn...,what are some of the things technicians can te...,0
11,11,23,24,how do i read and find my youtube comments?,how can i see all my youtube comments?,1
12,12,25,26,what can make physics easy to learn?,how can you make physics easy to learn?,1
13,13,27,28,what was your first sexual experience like?,what was your first sexual experience?,1
14,14,29,30,what are the laws to change your status from a...,what are the laws to change your status from a...,0

In [98]:
ps = PorterStemmer()
data['question1'] = data['question1'].astype(str).str.split()
data['question2'] = data['question2'].astype(str).str.split()
data.question1.apply(lambda x: [ps.stem(word) for word in x])
data.question2.apply(lambda x: [ps.stem(word) for word in x])

0        [what, is, the, step, by, step, guid, to, inve...
1        [what, would, happen, if, the, indian, govern,...
2        [how, can, internet, speed, be, increas, by, h...
3        [find, the, remaind, when, [math]23^{24}[/math...
4           [which, fish, would, surviv, in, salt, water?]
                               ...
99991          [how, did, you, come, out, of, depression?]
99992         [is, the, conjur, base, on, a, true, story?]
99993    [what, are, the, entrepreneuri, opportun, that...
99994    [which, is, the, best, countri, to, do, an, ms...
99995    [how, can, you, know, when, someon, love, you,...
Name: question2, Length: 99996, dtype: object

In [99]:
data

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,"[what, is, the, step, by, step, guide, to, inv...","[what, is, the, step, by, step, guide, to, inv...",0
1,1,3,4,"[what, is, the, story, of, kohinoor, (koh-i-no...","[what, would, happen, if, the, indian, governm...",0
2,2,5,6,"[how, can, i, increase, the, speed, of, my, in...","[how, can, internet, speed, be, increased, by,...",0
3,3,7,8,"[why, am, i, mentally, very, lonely?, how, can...","[find, the, remainder, when, [math]23^{24}[/ma...",0
4,4,9,10,"[which, one, dissolve, in, water, quikly, suga...","[which, fish, would, survive, in, salt, water?]",0
...,...,...,...,...,...,...
99991,99991,198420,198421,"[how, can, i, come, out, of, my, depression?]","[how, did, you, come, out, of, depression?]",0
99992,99992,198422,198423,"[is, conjuring, based, on, a, true, story?]","[is, the, conjuring, based, on, a, true, story?]",1
99993,99993,198424,198425,"[what, business, opportunities, may, arise, as...","[what, are, the, entrepreneurial, opportunitie...",1
99994,99994,198426,198427,"[which, country, is, best, for, ms, in, mechan...","[which, is, the, best, country, to, do, an, ms...",1
99995,99995,198428,198429,"[how, would, you, know, someone, really, loves...","[how, can, you, know, when, someone, loves, yo...",0

In [38]:
X = data.drop(['is_duplicate'], axis=1)
y = data['is_duplicate']
X, X_test, y, y_test = train_test_split(X, y, test_size=0.4, random_state=241)